package com.hati.cashcard;

import com.jayway.jsonpath.DocumentContext;
import com.jayway.jsonpath.JsonPath;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.annotation.DirtiesContext;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.annotation.DirtiesContext.*;

import java.net.URI;

//integration test for the whole application, use random port to avoid conflict
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD) // reset the database after each test method, so that
                                                              // tests do not interfere with each other

class CashCardApplicationTests {
    @Autowired // injects TestRestTemplate instance automatically
    TestRestTemplate restTemplate; // simulates a client sending HTTP requests to the application and receiving
                                   // responses

    @Test
    void shouldReturnACashCardWhenDataIsSaved() {
        // simulates a GET request to /cashcards/99
        ResponseEntity<String> response = restTemplate.getForEntity("/cashcards/99", String.class);
        // check the status code
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        // check the id
        DocumentContext documentContext = JsonPath.parse(response.getBody());
        Number id = documentContext.read("$.id");
        assertThat(id).isEqualTo(99);
        // check the amount
        Double amount = documentContext.read("$.amount");
        assertThat(amount).isEqualTo(123.45);
    }

    @Test
    // POST - create data - get location - GET - verify data
    void shouldCreateANewCashCard() {
        CashCard newCashCard = new CashCard(null, 250.00); // null because id is generated by database
        // simulates a client sending a POST request to create a new cash card
        ResponseEntity<Void> createResponse = restTemplate.postForEntity("/cashcards", newCashCard, Void.class);
        assertThat(createResponse.getStatusCode()).isEqualTo(HttpStatus.CREATED); // expecting 201 for POST request

        // get location header for newly created cash card(Location: /cashcards/{id})
        URI locationofNewCashCard = createResponse.getHeaders().getLocation();
        // same GET request as above
        ResponseEntity<String> getResponse = restTemplate.getForEntity(locationofNewCashCard, String.class);
        assertThat(getResponse.getStatusCode()).isEqualTo(HttpStatus.OK);

        DocumentContext documentContext = JsonPath.parse(getResponse.getBody());
        Number id = documentContext.read("$.id");
        Double amount = documentContext.read("$.amount");

        assertThat(id).isNotNull();
        assertThat(amount).isEqualTo(250.00);
    }

    @Test
    void shouldReturnAllCashCardsWhenListIsRequested() {
        ResponseEntity<String> response = restTemplate.getForEntity("/cashcards", String.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
    }

}